"""add duration minutes

Revision ID: 54cfd65fac47
Revises: 9a240c34eee8
Create Date: 2026-06-06 23:45:06.353106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cfd65fac47'
down_revision: Union[str, None] = '9a240c34eee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'duration_minutes')
    # ### end Alembic commands ###
